### ISSUE TITLE
Build nodes and user nodes may require different container lookup configs

### ISSUE THREAD

**Issue by manics** [yuvipanda/cryptnono#23]
OVH has separate build and user K8s nodes. All K8s nodes have containerd so execwhacker should always be able to lookup the parent container for a kill K8s process, but only the build nodes have Docker (-in-docker). This means if we want to lookup the parent container for a process during a build the build nodes need a separate config:

https://github.com/jupyterhub/mybinder.org-deploy/pull/2882/files

Potential solutions:
- Deploy cryptnono twice in mybinder.org-deploy, using different nodeSelectors. The main downside is having to duplicate the cryptnono config
- Support deploying multiple instances of the daemonset in the cryptnono Helm chart with different nodeSelectors and docker path configs
- Don't lookup the parent container during builds

**Comment by yuvipanda** [comment]
Another solution is that we don't make cri vs docker configurable - just try cri first, and docker next if not found in cri.

**Comment by manics** [comment]
The problem is we need to mount the host dockerd socket into the cryptnono pod. If it;s configured as a host volume but it doesn't exist the pod can't start.

**Comment by yuvipanda** [comment]
@manics thoughts on mounting the entire filesystem? Particularly what the security implications would be.

**Comment by manics** [comment]
That should work! I don't think it significantly changes the security risks. The cryptnono container already requires privileges to run eBPF so can pretty much gain access to everything already. Mounting the containerd socket also gives you privileged access to the host.

**Comment by yuvipanda** [comment]
@manics I think that's the way to go!
